### ISSUE TITLE
400 error on login

### ISSUE THREAD

**Issue by gboudreau** [bvanheu/pytoutv#115]
$ toutv login me@hotmail.com
    Password: 
    Unable to login "Unexpected HTTP response code 400 for "https://services.radio-canada.ca/auth/oauth/v2/authorize""

On the web, I can login just fine.
Same using the mobile app on Android.
It's just pytoutv that gives me an error...

**Comment by simark** [comment]
I get the error too.

**Comment by Extarys** [comment]
I get:
`Unable to login "Unexpected HTTP response code 200 for "https://services.radio-canada.ca/auth/oauth/v2/authorize""`
Should I open a different issue?

**Comment by gboudreau** [comment]
No, I get the same error as you now.
Will take a look today if I can.

**Comment by gboudreau** [comment]
Looks like the login flow changed; I checked what the Android app did, and replicated that. Was close enough to what we were doing already.

**Comment by pducharme** [comment]
How to isntall the fix ?  I installed by issuing sudo pip3 install pytoutv (got version 3. something), but still get the same error HTTP 200.

**Comment by simark** [comment]
> How to isntall the fix ? I installed by issuing sudo pip3 install pytoutv (got version 3. something), but still get the same error HTTP 200.

@pducharme, I created a new release, so you should be able to use `pip3 install --upgrade pytoutv` to get the new version now.

**Comment by Extarys** [comment]
Awesome thanks

**Comment by pducharme** [comment]
Works fine with the new version btw.
