### ISSUE TITLE
Add 720p to quality list

### ISSUE THREAD

**Issue by danyboy666** [bvanheu/pytoutv#122]
Would it be possible to add this?
  
`db666@homeshare:~$ toutv info "Les grands reportages" S24E02
Les grands reportages
La course vers l'intelligence artificielle  [S24E02]

Ce documentaire australien démontre comment l'intelligence artificielle va
changer notre travail, car de nouvelles recherches montrent combien de ce que
nous faisons pourrait être fait par des robots.

Infos:

  * Air date: 2018-01-03
  * Available qualities:
    * 461 kbps (480x270)
    * 561 kbps (512x288)
    * 925 kbps (640x360)
    * 1324 kbps (852x480)
    * 2124 kbps (852x480)
`

**Comment by simark** [comment]
IIRC 720p is a tou.tv extra feature, so you need to have a tou.tv extra account.  You then need to log in using "toutv login <username/email>", and then you'll be able to see and download the 720p version:

```
$ toutv info "Les grands reportages" S24E02
Les grands reportages
Épisode 02  [S24E02]

Ce documentaire australien démontre comment l'intelligence artificielle va
changer notre travail, car de nouvelles recherches montrent combien de ce que
nous faisons pourrait être fait par des robots.


Infos:

  * Air date: 3 janvier 2018
  * Available qualities:
    * 461 kbps (480x270)
    * 561 kbps (512x288)
    * 925 kbps (640x360)
    * 1324 kbps (852x480)
    * 2124 kbps (852x480)
    * 3124 kbps (1280x720)

```

**Comment by danyboy666** [comment]
I should've read the read.me file :) thank you very much it's working.
