### ISSUE TITLE
pytoutv in a Docker image

### ISSUE THREAD

**Issue by anthonydahanne** [bvanheu/pytoutv#126]
Hello, 
maybe an issue is not the right place, but I've packaged pytoutv in a Docker container, see : https://github.com/anthonydahanne/toutv for examples and how to use it.

It should be updated frequently (the image is available from : https://hub.docker.com/r/anthonydahanne/toutv/ ) and if you want to use the Dockerfile and push the image to your own Github repository, let me know.

I can also help with it all - je suis sur Montréal, autour d'une bière çà me ferait plaisir d'en parler !

**Comment by simark** [comment]
Bonjour Anthony,

Awesome!  Feel free to open a pull request if you'd like the Dockerfile to be part of this repo (or for any other improvement).

**Comment by anthonydahanne** [comment]
c'est fait :-) #127

once merged, I'll change the DockerHub automated build located at : https://hub.docker.com/r/anthonydahanne/toutv/ to get the Dockerfile from this repo instead of mine.

If one day you want to create a pytoutv account on DockerHub, I'll stop building mine and point to yours.
Hope that helps !
