### ISSUE TITLE
Cannot fetch "Extra" content

### ISSUE THREAD

**Issue by ocafebabe** [bvanheu/pytoutv#30]
There is no way to fetch content from the "Extra" section!

**Comment by antdes45** [comment]
See https://github.com/scarpentier/toutv-extra

This one will output the link to master.m3u8 to any 'ffmpeg' executable (cmd/bat/exe) in the same folder. However, ffmpeg won't download the file.

Tested overwriting 'url' in get_playlist_cookies() with the provided master.m3u8. Works.

**Comment by bvanheu** [comment]
I've provided a pull request for downloading content in 720p, but i'm not sure how we can fetch extra content using the JSON API.

See pull request #61

**Comment by gboudreau** [comment]
This has been merged into master a while ago. Closing.
