### ISSUE TITLE
Read resolution from m3u8

### ISSUE THREAD

**Issue by simark** [bvanheu/pytoutv#35]
The m3u8 lists the resolution along with the bitrate. We should use it to display in the bitrate chooser, instead of hardcoded values.

Example:
# EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3124000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"

**Comment by eepp** [comment]
Is this fixed?

**Comment by simark** [comment]
It seems so.
