### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED on newer episodes

### ISSUE THREAD

**Issue by matjolic** [bvanheu/pytoutv#49]
Episodes of the latest season, since January 2015 (maybe others, but this seems consistent), are failing to download with an SSL certificate verification failure.

Unknown error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

I'm guessing the network has yet again changed its protocol, but I am uncertain as to how to debug this.

**Comment by simark** [comment]
Hi @matjolic,

First, as a sanity check, could you have the same problem as #47? It was on Debian Jessie, the CA certificates were messed up or not up to date, and updating or reconfiguring the ca-certificates package fixed the problem.

Thanks.

**Comment by simark** [comment]
Also, please provide the exact command you use to download, so we can try it.

**Comment by matjolic** [comment]
I'm looking into the ca-certificates package issue, I too am on Debian Jessie.

Here's an example command that gave this error: 

toutv fetch -q MAX 'infoman' s15e17

**Comment by matjolic** [comment]
I can confirm that this was caused by the GTE_CyberTrust_Global_Root.pem certificate being disabled in the ca-certificates (20141019) package, on debian jessie at least.

**Comment by simark** [comment]
Since this seems to affect multiple users, I wonder if we should catch the
error and display an appropriate message that would guide to resolve the
issue.
