### ISSUE TITLE
Unknown error: unpickling stack underflow

### ISSUE THREAD

**Issue by MagicFab** [bvanheu/pytoutv#52]
I've installed pytoutv v 2.3.0 on Debian Jessie, following instructions at https://github.com/bvanheu/pytoutv#ubuntu-and-debian

After a few succesful downloads, I tried a third simultaneous fetch, I now get this error for any operation (list, search, etc):
Unknown error: unpickling stack underflow

**Comment by simark** [comment]
Hi Fabian,

The only place where pickling (serializing a Python data structure to a file) occurs in pytoutv, as far as I know, is for caching. If you run multiple instances of the toutv command-line tool simultaneously, they are probably colliding while trying to read/write the cache file. But that's just a guess. In the current state, it's probably not safe to run multiple instances of the CLI tool concurrently.

**Comment by eepp** [comment]
This should be handled properly, using a writer lock or something.

In the meantime, you may use the `-n` option to skip the cache. Please reply if this helps.

**Comment by MagicFab** [comment]
Ah! I figured. It's a bit puzzling that some simultaneuous downloads worked. Perhaps when simultaneous fetch operations happen cache should be disabled ? A more descriptive error message including the workaround (using -n) could help.

**Comment by MagicFab** [comment]
It seems -n is not implemented for toutv list, where I still get the same error.

$ toutv list
Unknown error: unpickling stack underflow
$ toutv -n list
usage: toutv [-h] [-V] {list,info,search,fetch} ...
toutv: error: unrecognized arguments: -n

**Comment by eepp** [comment]
Damn, I'll work on a patch today or tomorrow and include your idea of not using the cache on multiple instances.

**Comment by MagicFab** [comment]
I am not saying I need multiple-instance fetching working, in fact this may hurt tou.tv' s servers more than help. I usually queue occasional  downloads so I don' t mind, but knowing why an error (or intended limitation) happens / works is still useful.
Perhaps it needs to be considered if more than a couple multi-fetch operations would be allowed. In any case people wanting to do this regardless of server impact would probably use different, separate systems.

**Comment by eepp** [comment]
Fixed by b0a3b33.

Parallel fetching is now possible.

The CLI prints a warning when it's not using the cache.

By the way, you tried `toutv -n list`, whereas `-n` is an option to `list`: `toutv list -n` works fine when the cache is not available (although it is automated thanks to this new commit).

I don't believe we need to impose any limit on the number of parallel network operations; it is the user's responsibility to manage this.
