### ISSUE TITLE
Lists: remove trailing ':' after IDs

### ISSUE THREAD

**Issue by eepp** [bvanheu/pytoutv#57]
The CLI list currently looks like this:
 
    ...
    2424966275: Sur le Yangzi
    2339675742: Synthétiseur
    2296651836: Tabula Rasa
    2422158697: The pamplemousse
    2424966628: Ti-Mé Show
    2424966325: Toi et moi
    2424966549: Toi, t'es-tu Lucky?
    ...

What's often done is double-clicking the ID, which also selects the trailing `:` character with some terminal emulators, and middle-clicking after having typed `toutv list ` to list the episodes of this show. Then the trailing `:` should not be pasted, so it should be removed from the list output, because it's very annoying.

**Comment by simark** [comment]
It's a good idea in itself. Although it would be nice to find an easier workflow, that does not involve copying random numbers.

**Comment by eepp** [comment]
I agree, the workflow sucks. Perhaps a global `--interactive`/`-i` option?

**Comment by simark** [comment]
We could add a switch for an interactive mode to keep backwards compatibility. But if such a mode is implemented, it would be worth it to bump the major and make it the default (while keeping a way to make it unattended as well).

**Comment by eepp** [comment]
I'm not sure. Users could have scripts right now using `toutv` in an automated way, and the default interactive mode would break their scripts.

**Comment by simark** [comment]
Which is why bumping the major would be necessary. It's a major redesign of the interface.

**Comment by eepp** [comment]
I know. I'm questioning the impacts of such a major bump on the users.
