### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by davidonlaptop** [bvanheu/pytoutv#60]
Hi guys,

I having trouble downloading an episode:

```
$ toutv fetch -q MAX -d epi7 "Dans l'oeil du dragon" "S03E07"
Dans.l'oeil.du.dragon.S03E07.Episode.7.2124kbps.ts                                 118.7 MiB    44/260 [#########-------------------------------------------]  16%Unknown error: HTTPConnectionPool(host='toutvuniver1-vh.akamaihd.net', port=80): Read timed out.
```

Might be related to #36 . A resume feature would be great; do you know if it is supported by Tou.Tv ?

L'ETS est partout!

Merci Vanheu!

**Comment by eepp** [comment]
There is a resume feature. I don't think it's released yet, but it's in the Git master.

Clone the repo and do a [manual setup](https://github.com/bvanheu/pytoutv#using-setuppy).

Then, you only need to issue the same command again to resume the download.

**Comment by davidonlaptop** [comment]
I tried with branch master, it does not seems to work.

```
⌂31% [:~/Movies/Oeil_du_Dragon] $ toutv fetch -q MAX -d epi7 "Dans l'oeil du dragon" "S03E07"
Destination file exists (use -f to force)
⌂33% [:~/Movies/Oeil_du_Dragon] 2 $ toutv fetch --help
usage: toutv fetch [-h] [-b BITRATE] [-d DIRECTORY] [-f]
                   [-q {MIN,AVERAGE,MAX}] [-u]
                   emission [episode]

positional arguments:
  emission              Emission name to fetch
  episode               Episode name to fetch

optional arguments:
  -h, --help            show this help message and exit
  -b BITRATE, --bitrate BITRATE
                        Video bitrate (default: use default quality)
  -d DIRECTORY, --directory DIRECTORY
                        Output directory (default: CWD)
  -f, --force           Overwrite existing output file
  -q {MIN,AVERAGE,MAX}, --quality {MIN,AVERAGE,MAX}
                        Video quality (default: AVERAGE)
  -u, --url             Fetch an episode using a TOU.TV URL
```

Which branch should I be using?

**Comment by davidonlaptop** [comment]
I had a quick look a branch develop, but there is no setup.py file.

**Comment by davidonlaptop** [comment]
Forget about it, I messed up :-)

I confirm that the resume feature works with master branch.

Is there a way to force it to retry automatically?

**Comment by eepp** [comment]
Yes:

    while true; do
        if toutv fetch -q MAX -d epi7 "Dans l'oeil du dragon" "S03E07"; then
            break
        fi
    done

:wink:

**Comment by davidonlaptop** [comment]
good call :-p
