### ISSUE TITLE
doesn't install on Windows

### ISSUE THREAD

**Issue by sirber** [bvanheu/pytoutv#62]
C:\Users\sirber\Documents\GitHub\pytoutv>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to pytoutv.egg-info\requires.txt
writing entry points to pytoutv.egg-info\entry_points.txt
writing dependency_links to pytoutv.egg-info\dependency_links.txt
writing top-level names to pytoutv.egg-info\top_level.txt
writing pytoutv.egg-info\PKG-INFO
reading manifest file 'pytoutv.egg-info\SOURCES.txt'
writing manifest file 'pytoutv.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
creating build\bdist.win32\egg\toutv
copying build\lib\toutv\bos.py -> build\bdist.win32\egg\toutv
copying build\lib\toutv\cache.py -> build\bdist.win32\egg\toutv
copying build\lib\toutv\client.py -> build\bdist.win32\egg\toutv
copying build\lib\toutv\config.py -> build\bdist.win32\egg\toutv
copying build\lib\toutv\dl.py -> build\bdist.win32\egg\toutv
copying build\lib\toutv\exceptions.py -> build\bdist.win32\egg\toutv
copying build\lib\toutv\m3u8.py -> build\bdist.win32\egg\toutv
copying build\lib\toutv\mapper.py -> build\bdist.win32\egg\toutv
copying build\lib\toutv\transport.py -> build\bdist.win32\egg\toutv
copying build\lib\toutv\__init__.py -> build\bdist.win32\egg\toutv
creating build\bdist.win32\egg\toutvcli
copying build\lib\toutvcli\app.py -> build\bdist.win32\egg\toutvcli
copying build\lib\toutvcli\app_test.py -> build\bdist.win32\egg\toutvcli
copying build\lib\toutvcli\progressbar.py -> build\bdist.win32\egg\toutvcli
copying build\lib\toutvcli\__init__.py -> build\bdist.win32\egg\toutvcli
creating build\bdist.win32\egg\toutvqt
copying build\lib\toutvqt\about_dialog.py -> build\bdist.win32\egg\toutvqt
copying build\lib\toutvqt\app.py -> build\bdist.win32\egg\toutvqt
copying build\lib\toutvqt\choose_bitrate_dialog.py -> build\bdist.win32\egg\tout
vqt
copying build\lib\toutvqt\config.py -> build\bdist.win32\egg\toutvqt
creating build\bdist.win32\egg\toutvqt\dat
creating build\bdist.win32\egg\toutvqt\dat\icons
copying build\lib\toutvqt\dat\icons\about_action.png -> build\bdist.win32\egg\to
utvqt\dat\icons
copying build\lib\toutvqt\dat\icons\cancel_action.png -> build\bdist.win32\egg\t
outvqt\dat\icons
copying build\lib\toutvqt\dat\icons\open_action.png -> build\bdist.win32\egg\tou
tvqt\dat\icons
copying build\lib\toutvqt\dat\icons\open_dir_action.png -> build\bdist.win32\egg
\toutvqt\dat\icons
copying build\lib\toutvqt\dat\icons\preferences_action.png -> build\bdist.win32\
egg\toutvqt\dat\icons
copying build\lib\toutvqt\dat\icons\quit_action.png -> build\bdist.win32\egg\tou
tvqt\dat\icons
copying build\lib\toutvqt\dat\icons\refresh_emissions_action.png -> build\bdist.
win32\egg\toutvqt\dat\icons
copying build\lib\toutvqt\dat\icons\remove_item_action.png -> build\bdist.win32\
egg\toutvqt\dat\icons
copying build\lib\toutvqt\dat\icons\toutv.png -> build\bdist.win32\egg\toutvqt\d
at\icons
creating build\bdist.win32\egg\toutvqt\dat\ui
copying build\lib\toutvqt\dat\ui\about_dialog.ui -> build\bdist.win32\egg\toutvq
t\dat\ui
copying build\lib\toutvqt\dat\ui\choose_bitrate_dialog.ui -> build\bdist.win32\e
gg\toutvqt\dat\ui
copying build\lib\toutvqt\dat\ui\emission_infos_widget.ui -> build\bdist.win32\e
gg\toutvqt\dat\ui
copying build\lib\toutvqt\dat\ui\episode_infos_widget.ui -> build\bdist.win32\eg
g\toutvqt\dat\ui
copying build\lib\toutvqt\dat\ui\main_window.ui -> build\bdist.win32\egg\toutvqt
\dat\ui
copying build\lib\toutvqt\dat\ui\preferences_dialog.ui -> build\bdist.win32\egg\
toutvqt\dat\ui
copying build\lib\toutvqt\dat\ui\season_infos_widget.ui -> build\bdist.win32\egg
\toutvqt\dat\ui
copying build\lib\toutvqt\downloads_itemdelegate.py -> build\bdist.win32\egg\tou
tvqt
copying build\lib\toutvqt\downloads_tablemodel.py -> build\bdist.win32\egg\toutv
qt
copying build\lib\toutvqt\downloads_tableview.py -> build\bdist.win32\egg\toutvq
t
copying build\lib\toutvqt\download_manager.py -> build\bdist.win32\egg\toutvqt
copying build\lib\toutvqt\emissions_treemodel.py -> build\bdist.win32\egg\toutvq
t
copying build\lib\toutvqt\emissions_treeview.py -> build\bdist.win32\egg\toutvqt

copying build\lib\toutvqt\infos_frame.py -> build\bdist.win32\egg\toutvqt
copying build\lib\toutvqt\main_window.py -> build\bdist.win32\egg\toutvqt
copying build\lib\toutvqt\preferences_dialog.py -> build\bdist.win32\egg\toutvqt

copying build\lib\toutvqt\settings.py -> build\bdist.win32\egg\toutvqt
copying build\lib\toutvqt\utils.py -> build\bdist.win32\egg\toutvqt
copying build\lib\toutvqt\__init__.py -> build\bdist.win32\egg\toutvqt
byte-compiling build\bdist.win32\egg\toutv\bos.py to bos.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutv\cache.py to cache.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutv\client.py to client.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutv\config.py to config.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutv\dl.py to dl.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutv\exceptions.py to exceptions.cpython-3
5.pyc
byte-compiling build\bdist.win32\egg\toutv\m3u8.py to m3u8.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutv\mapper.py to mapper.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutv\transport.py to transport.cpython-35.
pyc
byte-compiling build\bdist.win32\egg\toutv\__init__.py to __init__.cpython-35.py
c
byte-compiling build\bdist.win32\egg\toutvcli\app.py to app.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvcli\app_test.py to app_test.cpython-35
.pyc
byte-compiling build\bdist.win32\egg\toutvcli\progressbar.py to progressbar.cpyt
hon-35.pyc
byte-compiling build\bdist.win32\egg\toutvcli\__init__.py to __init__.cpython-35
.pyc
byte-compiling build\bdist.win32\egg\toutvqt\about_dialog.py to about_dialog.cpy
thon-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\app.py to app.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\choose_bitrate_dialog.py to choose_
bitrate_dialog.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\config.py to config.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\downloads_itemdelegate.py to downlo
ads_itemdelegate.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\downloads_tablemodel.py to download
s_tablemodel.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\downloads_tableview.py to downloads
_tableview.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\download_manager.py to download_man
ager.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\emissions_treemodel.py to emissions
_treemodel.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\emissions_treeview.py to emissions_
treeview.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\infos_frame.py to infos_frame.cpyth
on-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\main_window.py to main_window.cpyth
on-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\preferences_dialog.py to preference
s_dialog.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\settings.py to settings.cpython-35.
pyc
byte-compiling build\bdist.win32\egg\toutvqt\utils.py to utils.cpython-35.pyc
byte-compiling build\bdist.win32\egg\toutvqt\__init__.py to __init__.cpython-35.
pyc
creating build\bdist.win32\egg\EGG-INFO
copying pytoutv.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying pytoutv.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying pytoutv.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying pytoutv.egg-info\entry_points.txt -> build\bdist.win32\egg\EGG-INFO
copying pytoutv.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying pytoutv.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\pytoutv-2.3.0-py3.5.egg' and adding 'build\bdist.win32\egg' to it

removing 'build\bdist.win32\egg' (and everything under it)
Processing pytoutv-2.3.0-py3.5.egg
Removing c:\users\sirber\appdata\local\programs\python\python35-32\lib\site-pack
ages\pytoutv-2.3.0-py3.5.egg
Copying pytoutv-2.3.0-py3.5.egg to c:\users\sirber\appdata\local\programs\python
\python35-32\lib\site-packages
pytoutv 2.3.0 is already the active version in easy-install.pth
Installing toutv-script.py script to C:\Users\sirber\AppData\Local\Programs\Pyth
on\Python35-32\Scripts
Installing toutv.exe script to C:\Users\sirber\AppData\Local\Programs\Python\Pyt
hon35-32\Scripts
Installing toutv.exe.manifest script to C:\Users\sirber\AppData\Local\Programs\P
ython\Python35-32\Scripts
Installing qtoutv-script.pyw script to C:\Users\sirber\AppData\Local\Programs\Py
thon\Python35-32\Scripts
Installing qtoutv.exe script to C:\Users\sirber\AppData\Local\Programs\Python\Py
thon35-32\Scripts
Installing qtoutv.exe.manifest script to C:\Users\sirber\AppData\Local\Programs\
Python\Python35-32\Scripts

Installed c:\users\sirber\appdata\local\programs\python\python35-32\lib\site-pac
kages\pytoutv-2.3.0-py3.5.egg
Processing dependencies for pytoutv==2.3.0
Searching for pycrypto>=2.0.0
Reading https://pypi.python.org/simple/pycrypto/
Best match: pycrypto 2.6.1
Downloading https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.ta
r.gz#md5=55a61a054aa66812daf5161a0d5d7eda
Processing pycrypto-2.6.1.tar.gz
Writing C:\Users\sirber\AppData\Local\Temp\easy_install-qcn51fml\pycrypto-2.6.1\
setup.cfg
Running pycrypto-2.6.1\setup.py -q bdist_egg --dist-dir C:\Users\sirber\AppData\
Local\Temp\easy_install-qcn51fml\pycrypto-2.6.1\egg-dist-tmp-b5oi4mfl
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

error: Setup script exited with error: [WinError 2] The system cannot find the f
ile specified

**Comment by sirber** [comment]
same thing via pip:

    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

**Comment by eepp** [comment]
Oh.. I don't think this has ever been tested on Windows. A pull request is welcome if you find your way to a working pytoutv on Windows.

**Comment by antoinedeschenes** [comment]
Install pycrypto first
https://github.com/axper/python3-pycrypto-windows-installer?files=1 and
then use pip.

**Comment by sirber** [comment]
Last time I used it, it was on windows. maybe one year earlier.
Trying the binary option :)

**Comment by sirber** [comment]
that worked, thank you!

C:\Users\sirber>pip install pytoutv
Downloading/unpacking pytoutv
  Running setup.py (path:C:\Users\sirber\AppData\Local\Temp\pip_build_sirber\pyt
outv\setup.py) egg_info for package pytoutv

Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.0.0 in c:\
python34\lib\site-packages (from pytoutv)
Downloading/unpacking requests>=2.0.0 (from pytoutv)
Downloading/unpacking setuptools>=3.0 (from pytoutv)
Installing collected packages: pytoutv, requests, setuptools
  Running setup.py install for pytoutv

    Installing toutv-script.py script to C:\Python34\Scripts
    Installing toutv.exe script to C:\Python34\Scripts
    Installing toutv.exe.manifest script to C:\Python34\Scripts
    Installing qtoutv-script.pyw script to C:\Python34\Scripts
    Installing qtoutv.exe script to C:\Python34\Scripts
    Installing qtoutv.exe.manifest script to C:\Python34\Scripts
  Found existing installation: setuptools 2.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed pytoutv requests setuptools
Cleaning up...
