### ISSUE TITLE
timeout on https://api.tou.tv/v1/toutvapiservice.svc/json/GetEmissions

### ISSUE THREAD

**Issue by sirber** [bvanheu/pytoutv#63]
timeout on https://api.tou.tv/v1/toutvapiservice.svc/json/GetEmissions

would it be the website or a problem with python?

**Comment by antoinedeschenes** [comment]
The v1 api is always going up and down on the tou.tv website. Just wait a few minutes and it should come back.

**Comment by eepp** [comment]
Yes, perhaps 10 seconds is not enough for the timeout?

**Comment by antoinedeschenes** [comment]
I guess retries after timeout would be more appropriate. I bet the site won't answer if you don't send a new request after a while. I believe V2 would be a better solution, but not without rewriting half of the code.

**Comment by sirber** [comment]
same on windows. guess it's a toutv issue

**Comment by sirber** [comment]
Worked after retrying a few time. Could the script retry a finite number of times (like 10) in case of timeout?

**Comment by simark** [comment]
I still get a lot of them:

```
$ toutv -n list
Timeout error (10 s for "https://api.tou.tv/v1/toutvapiservice.svc/json/GetEmissions")
```

@antoinedeschenes: do you have any information about the v2 API?
