### ISSUE TITLE
Tou.tv EXTRA fetching

### ISSUE THREAD

**Issue by philalou** [bvanheu/pytoutv#64]
Hi all,

I am trying to fetch content from the EXTRA section of Tou.TV. I saw a previous post discussing the issue and I tried to find what I had to input in my Terminal to get this to work.

So far, I have tried to enter the following command line: 
toutv login -u username@email.com -p xxx

My terminal returns the following message:
usage: toutv [-h] [-V] {list,info,search,fetch} ...
toutv: error: argument command: invalid choice: 'login' (choose from 'list', 'info', 'search', 'fetch')

So I guess I am missing something somewhere to get this to work.

Just wanted to tell you that I am able to fetch videos from the actual Tou.TV website without any problem, thanks for this great tool!

Any help is appreciated!

**Comment by bvanheu** [comment]
You won't be able to fetch videos that are made available in the Extra section yet, only download videos in 720p. I will refer you to this project: https://github.com/scarpentier/toutv-extra

But if you want to fetch 720p content, you need to checkout the `feature/extra` by running `git checkout feature/extra` and rebuild your virtual env (if you only want to try it).

**Comment by philalou** [comment]
Thanks for your answer! Hopefully there will be a way at some point to get over this Extra section fetching story, especially when you have all the credentials to access the Extra section...

**Comment by gboudreau** [comment]
I made a new PR (#79) that allows downloading by using this command:
`toutv fetch --url [emission_url] [episode_url]`
We still can't load the episode or emission information for Extras, but I think most people just want fetch to work. The fetch file will be named `[emission_id].[episode_id].bitrate.ts`.

**Comment by gboudreau** [comment]
This has been merged into the master branch a while ago. Closing.
