### ISSUE TITLE
Save cache in proper folder instead of working dir on macOS

### ISSUE THREAD

**Issue by simark** [bvanheu/pytoutv#76]
This is the same issue as #19, but for macOS.  We need to find the appropriate place to put our cache file.

This link could help: https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1

**Comment by gboudreau** [comment]
Mac also uses XDG, so using `$XDG_CACHE_HOME/toutv/` on Mac, same as Linux, is fine.
A simple change to do just that is included in PR #79 (could be cherry-picked, if you want this in master).

**Comment by simark** [comment]
Fixed with f134cfe.
