### ISSUE TITLE
Versionize the content of the cache

### ISSUE THREAD

**Issue by simark** [bvanheu/pytoutv#81]
If we change the format of the content in the cache, it could break when a user updates its client.  If the new version of the client uses a different data layout than the previous versions, it will probably fail somewhere.  We should save a cache format version (an number that we increment every time we change its layout) and check it when loading it.  If the version from the cache file is older than the current version, we simply flush the cache.

**Comment by gboudreau** [comment]
This was added in d1fc43d469ec462819a44ad4dae38a6c17324450
