### ISSUE TITLE
Timeout error during search

### ISSUE THREAD

**Issue by gboudreau** [bvanheu/pytoutv#98]
Search is the only function that still use the old API.
That old API sometimes simply times out.

Error is:

    Timeout error (20 s for "https://api.tou.tv/v1/toutvapiservice.svc/json/SearchTerms?query=...)

To work around this, we should lower the timeout for that API call, and just retry it a few times if we get Timeout errors.

**Comment by simark** [comment]
When you hit the search button in the Android application, it downloads the whole list of content from the `/search` API endpoint (which we already use for listing stuff), and I guess it does the search all client side. I think we should do the same, and stop using the old API altogether. WDYT?

**Comment by gboudreau** [comment]
Yes, that would be best.
